In [6]:
with open(r"C:\Research_Paper_Project\GPL570.annot.gz", "rt", encoding="utf-8", errors="ignore") as f:
    for i in range(30):
        print(f.readline())



W GPL570.annot \[ܶ~pl=u0;O{L,͵$%dڿTQui'HbUc{]I!gп7i;IlaQ}f+HDl}#woW3ϻ͏?v{*xSGݱHK-/em$v|ϲڥqd!:^~x>,nnuΟ CqٛW[}+ӢOZcGơbFl{)F?XwMGGA?>w渤w?gu쇞7|FL?O?AĿ~S#J(I̔h.aH@e4My;xP~eǲܝ졢UHo+lPYd	[3!503iWZgJݯN޿~XDڭN-C,S%,X護שּ[cq$Z#IfȚ0(,ss,ֈϘD}X*õ퇾ի3)67HᯊgnN(Ӛן,>Dc.v͔Ŀ3],6Ţs]fǑ`?eWNpssω'++0'ZPbqXn(a;h<Oa?6];Tb˘CRќQSe]b

sMWBlۢ|H"N.G9f]갗qy<t(d+5֛ɠìj+=7P`I%-[*1E0Ɋ8$0*p;WڊGP&6|59=6^)}W?lݪ[<DhUi]oszE]HX!l'Qݰi<G`M~iׇkkf

i]v/MJ'l;L{~$Jh>jCm_`lȥ5A_b'5~}q7[ t 2%1IB'&vc=M]aEC%ӦsȘv󜡍{,i9Bʦ ;oD8ϴrѹe[Pz>hlӍkIj;ϯӡk.W<̱~#ϋcWq^E􉮘o?|c^]5nz(ǆ_Áiq !pWyΞE2rـW~%W6L8[pMZUՠY5`F[M{qU%նv+ NWc%4c&T=꥚.=[풟eH_?Wo3b Ҵ2(W'V=I܋<x

*z	`?n~n?VYWe8`y#H^^od}ٲEZ3tiv8euM:ʶ|aKL\+,vQۄnh;hk@GȒƃx#c2?XuIK8:%^M;c38.mB'~>Duvw^1}c+ |o# ;Vi\19\]C^6%lsifױԨ ie(zze u8ǁIP,pz!W?E7oN{eKUuHFNi0i

ђ4nz±NAH{~=b}n@O*)3W32O|c؊b?Qbաtmb8d?$LBj!wUpȘD 31h4uZ*'ʿ->p<nf'ˑ^oS-j

PuƙH?:z	ͻgK]hYۍGY{ģtG@	ca_l,=);XF6мe5f ツH>

/FA(Ƙx<g)iD^V?!`h~ U

тu

D@Pz2t&0]+opҤLTH/Q`!\J㘋]Q\\,DAnF	k99: 3

\/JD|p]#MK5y"=}WZCMoЗ ֝L	?-1M9rLioG/FEF+X+7/dό5	5PQ%1	gi3$;c*)$1~C;XusVطc.FOO.|f ؗՇ{n2

NŴ0	;X-!a.'Q7d:bF"El|FE,&j4庱O

z5Pp)8mp_g[ xQ%5!78mE&.lě-@$8"dn3:шCHsbD

f6}PXQ;(vǴDН	!NNvmrAUAŦJ:ۛ

/mЌ1/^lbg/@ P_1DY|R

Zgϭ8S׸଻K&{/(HkXTVFju"&GśA냨x+yUM>Ը-0j[#1!;臖m E=FڤA0mXWy1х9|wS

{\/G،V^!7r

sDx~c?rU<6Uմ76_$Z0/tnPfxf$1^9f/q=<Tk%e@Y6Լ.~Q2BKu 	H6섒~

L.Nөk)486"̴؇am=A5Rs8(f#c^B

k:@u\PH5

F,-{

3c!8K;Ժ{ڊਝh'xBCA؃l샽g+^WLg/XS,]+0GW`,R@x00Z^F/oW̵vJ2@t@l@־

eZˊ.)f!=Ews6`/E;݃)PO&6ԿR0i<ѡ8lMk]&UŬJ~,$*>c(=.&^#`

Zt0`)

Ov1ǦW*x0T6eT[PԅUmyb<VM{Pv:ơ<<4<J

4K'-WF;3R:>T\w4#Y1jK_ֵ{ݮ5@$zNveރ<4EN{äG38HR=+w$"fiSw屩:t9D=s*Y ODÞjJ\B42ۃUhǬC"%yQ~b H䊞&vAPFo(}7dMBxi(I򟠃	ъOg

5bՃ!ITj

q#Q,$AD{K"8

jz@$k7H@K@jR<f׀Qzn[z_ׇ_f,?QHWF	w>Jpuq>Nn3Na"W	7ۻcN2a!uEz_3+у#J69_QN7u_%8 ⫫8?3 ˚Ny.fNIjgMΟD'GoϘwfu!x#vo3N6;4usK`LI{ ݛf=/-~usY=yAudWW	3#SDJoSʴQZ6%.Iw%]Leies'(DGL/r@1Kj]VsAiO3zi@jjoWʌ\MsOL@-Lų׷?VgQk=&/ӝcsdէO7d0qGcXxy>cˆ/ dR@"cs[Zӽ.C݋ި+ʲ_nd[]Y:p@dVlH]rcL]+i(2vPEa3M+{#YbHPgj(·B֤`[LA<6<e]m7b˯ruXmHf9{Q%lè1Tq[@kyD$:Ͳ=X+ ΥH1r,g	VJD_-B# >c[:ͥKRb7Y#"gKT-wm tIs(Rڲߍ

o>;]3dܼLW]=]<Mk?n[6XX;,-w䨥3y|d+Α]Ѩ(L<с2k!+vtvl9d]g'&vՒ^$/^ű/Er0U_ y}yx]

In [11]:
pip install gseapy

Collecting gseapy
  Downloading gseapy-1.3.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.13.0 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from gseapy) (1.26.4)
Requirement already satisfied: scipy in c:\users\iqra shaikh\anaconda3\lib\site-packages (from gseapy) (1.13.1)
Requirement already satisfied: pandas in c:\users\iqra shaikh\anaconda3\lib\site-packages (from gseapy) (2.2.2)
Requirement already satisfied: matplotlib>=2.2 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from gseapy) (3.8.4)
Requirement already satisfied: requests in c:\users\iqra shaikh\anaconda3\lib\site-packages (from gseapy) (2.32.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\iqra shaikh\appdata\roaming\python\python312\site-packages (from matplotlib>=2.2->gseapy) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from matplotlib>=2.2->gseapy) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\iqra shaikh\appdata\roaming\python\python312\site-packages (from matplotlib>=2.2->gseapy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from pandas->gseapy) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from pandas->gseapy) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from requests->gseapy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from requests->gseapy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from requests->gseapy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iqra shaikh\anaconda3\lib\site-packages (from requests->gseapy) (2024.7.4)
Requirement already satisfied: six>=1.5 in c:\users\iqra shaikh\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->gseapy) (1.16.0)
Downloading gseapy-1.3.0-cp312-cp312-win_amd64.whl (485 kB)
   ---------------------------------------- 0.0/485.2 kB ? eta -:--:--
   -- ------------------------------------ 30.7/485.2 kB 435.7 kB/s eta 0:00:02
   -- ------------------------------------ 30.7/485.2 kB 435.7 kB/s eta 0:00:02
   ------- ------------------------------- 92.2/485.2 kB 585.1 kB/s eta 0:00:01
   ------------------- -------------------- 235.5/485.2 kB 1.2 MB/s eta 0:00:01
   ------------------------------- -------- 378.9/485.2 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------  481.3/485.2 kB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 485.2/485.2 kB 1.7 MB/s eta 0:00:00
Installing collected packages: gseapy
Successfully installed gseapy-1.3.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
import gzip
import pandas as pd

# Read the annotation file
with gzip.open(
    r"C:\Research_Paper_Project\GPL570.annot.gz",
    "rt",
    encoding="utf-8",
    errors="ignore"
) as f:

    lines = f.readlines()

# Find where the platform table begins
start = None
for i, line in enumerate(lines):
    if line.startswith("!platform_table_begin"):
        start = i + 1
        break

# Load only the platform table
from io import StringIO

annotation = pd.read_csv(
    StringIO("".join(lines[start:])),
    sep="\t"
)

print(annotation.head())
print(annotation.columns)

          ID                                         Gene title  \
0  1007_s_at  microRNA 4640///discoidin domain receptor tyro...
1    1053_at                     replication factor C subunit 2
2     117_at       heat shock protein family A (Hsp70) member 6
3     121_at                                       paired box 8
4  1255_g_at                     guanylate cyclase activator 1A

      Gene symbol          Gene ID UniGene title UniGene symbol UniGene ID  \
0  MIR4640///DDR1  100616237///780           NaN            NaN        NaN
1            RFC2             5982           NaN            NaN        NaN
2           HSPA6             3310           NaN            NaN        NaN
3            PAX8             7849           NaN            NaN        NaN
4          GUCA1A             2978           NaN            NaN        NaN

                                    Nucleotide Title         GI  \
0  Human receptor tyrosine kinase DDR gene, compl...  1753221.0
1  Human replication factor C, 40-kDa subunit (A1...  1590810.0
2              Human heat-shock protein HSP70B' gene    35221.0
3                                H.sapiens Pax8 mRNA    38425.0
4  Homo sapiens guanylate cyclase activating prot...   623404.0

  GenBank Accession  ...  Platform_ORF  Platform_SPOTID Chromosome location  \
0            U48705  ...           NaN              NaN              6p21.3
1            M87338  ...           NaN              NaN             7q11.23
2            X51757  ...           NaN              NaN                1q23
3            X69699  ...           NaN              NaN                2q13
4            L36861  ...           NaN              NaN              6p21.1

                               Chromosome annotation  \
0  Chromosome 6, NC_000006.12 (30890883..30890972...
1  Chromosome 7, NC_000007.14 (74231502..74254458...
2  Chromosome 1, NC_000001.11 (161524540..161526897)
3  Chromosome 2, NC_000002.12 (113215997..1132789...
4    Chromosome 6, NC_000006.12 (42155377..42180083)

                                         GO:Function  \
0  ATP binding///collagen binding///collagen bind...
1  ATP binding///contributes_to DNA clamp loader ...
2  ATP binding///ATPase activity, coupled///enzym...
3  DNA binding///DNA binding///RNA polymerase II ...
4  calcium ion binding///calcium sensitive guanyl...

                                          GO:Process  \
0  branching involved in mammary gland duct morph...
1  DNA damage response, detection of DNA damage//...
2  NOT cellular heat acclimation///cellular respo...
3  anatomical structure morphogenesis///branching...
4  cellular response to calcium ion///phototransd...

                                        GO:Component  \
0  basolateral plasma membrane///extracellular ex...
1  Ctf18 RFC-like complex///DNA replication facto...
2  colocalizes_with COP9 signalosome///blood micr...
3                nucleoplasm///nucleoplasm///nucleus
4  photoreceptor disc membrane///photoreceptor in...

                                      GO:Function ID  \
0  GO:0005524///GO:0005518///GO:0005518///GO:0046...
1  GO:0005524///contributes_to GO:0003689///GO:00...
2  GO:0005524///GO:0042623///GO:0019899///GO:0031...
3  GO:0003677///GO:0003677///GO:0000978///GO:0000...
4               GO:0005509///GO:0008048///GO:0030249

                                       GO:Process ID  \
0  GO:0060444///GO:0007155///GO:0038063///GO:0038...
1  GO:0042769///GO:0006260///GO:0070987///GO:0042...
2  NOT GO:0070370///GO:0034605///GO:0034605///GO:...
3  GO:0009653///GO:0001658///GO:0071371///GO:0007...
4  GO:0071277///GO:0007602///GO:0031284///GO:0022...

                                     GO:Component ID
0  GO:0016323///GO:0070062///GO:0005615///GO:0005...
1               GO:0031390///GO:0005663///GO:0005654
2  colocalizes_with GO:0008180///GO:0072562///GO:...
3               GO:0005654///GO:0005654///GO:0005634
4               GO:0097381///GO:0001917///GO:0005886

[5 rows x 21 columns]
Index(['ID', 'Gene title', 'Gene symbol', 'Gene ID', 'UniGene title',
       'UniGene symbol', 'UniGene ID', 'Nucleotide Title', 'GI',
       'GenBank Accession', 'Platform_CLONEID', 'Platform_ORF',
       'Platform_SPOTID', 'Chromosome location', 'Chromosome annotation',
       'GO:Function', 'GO:Process', 'GO:Component', 'GO:Function ID',
       'GO:Process ID', 'GO:Component ID'],
      dtype='object')

C:\Users\IQRA SHAIKH\AppData\Local\Temp\ipykernel_19548\3731044143.py:24: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  annotation = pd.read_csv(

In [13]:
annotation = annotation[
    ["ID", "Gene symbol", "Gene title"]
]

annotation.head()

,ID,Gene symbol,Gene title
0,1007_s_at,MIR4640///DDR1,microRNA 4640///discoidin domain receptor tyro...
1,1053_at,RFC2,replication factor C subunit 2
2,117_at,HSPA6,heat shock protein family A (Hsp70) member 6
3,121_at,PAX8,paired box 8
4,1255_g_at,GUCA1A,guanylate cyclase activator 1A

In [14]:
top_genes = pd.read_csv(
    r"C:\Research_Paper_Project\Project\results\top_ranked_genes.csv"
)

annotated = top_genes.merge(
    annotation,
    left_on="Probe_ID",
    right_on="ID",
    how="left"
)

annotated.head(20)

,Probe_ID,F_Score,ID,Gene symbol,Gene title
0,211565_at,481.216276,211565_at,SH3GL3,"SH3 domain containing GRB2 like 3, endophilin A3"
1,243689_s_at,297.991104,243689_s_at,FRG1BP,"FSHD region gene 1 family member B, pseudogene"
2,1562755_at,276.654465,1562755_at,NaN,NaN
3,220232_at,208.893237,220232_at,SCD5,stearoyl-CoA desaturase 5
4,233103_at,204.729457,233103_at,NaN,NaN
5,224012_at,181.966976,224012_at,ANKRD20A4///ANKRD20A2///ANKRD20A3///ANKRD20A1,ankyrin repeat domain 20 family member A4///an...
6,1561754_at,178.021302,1561754_at,NaN,NaN
7,213715_s_at,168.059093,213715_s_at,KANK3,KN motif and ankyrin repeat domains 3
8,1562527_at,166.202618,1562527_at,LOC441666,zinc finger protein 91 pseudogene
9,235849_at,157.045139,235849_at,SCARA5,scavenger receptor class A member 5
10,229839_at,155.204279,229839_at,SCARA5,scavenger receptor class A member 5
11,205225_at,154.747647,205225_at,ESR1,estrogen receptor 1
12,210052_s_at,154.150485,210052_s_at,TPX2,"TPX2, microtubule nucleation factor"
13,223229_at,152.433065,223229_at,UBE2T,ubiquitin conjugating enzyme E2 T
14,204962_s_at,150.475367,204962_s_at,SLC35F6///CENPA,solute carrier family 35 member F6///centromer...
15,236359_at,147.003227,236359_at,SCN4B,sodium voltage-gated channel beta subunit 4
16,232538_at,144.942799,232538_at,NaN,NaN
17,238062_at,144.874211,238062_at,GPIHBP1,glycosylphosphatidylinositol anchored high den...
18,216153_x_at,143.558166,216153_x_at,RECK,reversion inducing cysteine rich protein with ...
19,220725_x_at,141.816131,220725_x_at,DNAH3,dynein axonemal heavy chain 3

In [15]:
annotated.to_csv(
    r"C:\Research_Paper_Project\Project\results\top_genes_annotated.csv",
    index=False
)

print("Annotated genes saved successfully!")

Annotated genes saved successfully!